services:
  temporally_backend:
    build:
      context: ./
      dockerfile: Dockerfile
    #    image: ryzeon/temporally:latest
    #    mem_limit: 512m
    ports:
      - "7645:7645"
    environment:
      - GOOGLE_CLIENT_ID=Key
      - GOOGLE_CLIENT_SECRET=Key
    restart: always
    depends_on:
      temporally_mongodb:
        condition: service_healthy

  temporally_mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=temporally
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_ROOT_USERNAME=root
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/temporally --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  mongodb_data: