services:
  temporally_backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ryzeon/temporally:latest
    #    mem_limit: 512m
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      temporally_mongodb:
        condition: service_healthy

  temporally_mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=temporally
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_ROOT_USERNAME=root
      - JWT_SECRET=example
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/temporally --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  mongodb_data: